tasks:
  - init: |
      echo "初始執行..."
      chmod +x ./sh/init_workspace.sh
      bash ./sh/init_workspace.sh
    command: |
      echo "回復執行..."
      chmod +x ./sh/startup_workspace.sh
      bash ./sh/startup_workspace.sh