version: "3"

services:
  nginx:
    image: nginx:stable
    container_name: nginx-static
    ports:
      - "3000:80"
    volumes:
      - /workspace/tomwu-gitpod-basic-environment/docker-data/nginx/static:/usr/share/nginx/html:ro
      - /workspace/tomwu-gitpod-basic-environment/docker-data/nginx/config/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: always
    
networks:
  web:
    external: true