version: "3"

services:
  file-browser:
    image: filebrowser/filebrowser:latest
    ports:
      - 5999:80
    volumes:
      - ${VOLUMES_ROOT}:/srv
      - ${VOLUMES_ROOT}/file-browser/config:/config
      - ${VOLUMES_ROOT}/file-browser/database:/database
    environment:
      - PUID=0
      - PGID=27
    restart: always

networks:
  web:
    external: true